In [13]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Import the requests library.
import requests


# Import citipy and api key
from citipy import citipy
from config import weather_api_key, g_key

In [14]:
# Import the datetime module from the datetime library.
import time
from datetime import datetime

In [15]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs

In [16]:
# Adding the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [5]:
# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=b721cc4ca5a458eeffd785a45371f4e0

In [6]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

46

In [7]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

# Loop through all the cities in our list.
for i in range(len(cities)):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
    # Create endpoint URL with each city.
    city_url = url + "&q=" + cities[i]
    
    # Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")
    
     # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
     # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_wdescription = city_weather["weather"][0]["description"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Current Description": city_wdescription,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country})
                          

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | ushtobe
Processing Record 2 of Set 1 | attawapiskat
City not found. Skipping...
Processing Record 3 of Set 1 | coihaique
Processing Record 4 of Set 1 | feijo
Processing Record 5 of Set 1 | tilichiki
Processing Record 6 of Set 1 | hermanus
Processing Record 7 of Set 1 | khatanga
Processing Record 8 of Set 1 | rikitea
Processing Record 9 of Set 1 | port alfred
Processing Record 10 of Set 1 | faanui
Processing Record 11 of Set 1 | mataura
Processing Record 12 of Set 1 | ushuaia
Processing Record 13 of Set 1 | airai
Processing Record 14 of Set 1 | ilulissat
Processing Record 15 of Set 1 | torbay
Processing Record 16 of Set 1 | arraial do cabo
Processing Record 17 of Set 1 | erzin
Processing Record 18 of Set 1 | waddan
Processing Record 19 of Set 1 | saldanha
Processing Record 20 of Set 1 | iqaluit
Processing Record 21 of Set 1 | namatanai
Processing Record 22 of Set 1 | vaini
Processing Record 23 of Set 1 | yellowknife
Processing Record 24 of Set 1 | carutapera
Processing Record 25 of Set 1 | isperih
Processing Record 26 of Set 1 | kahului
Processing Record 27 of Set 1 | butaritari
Processing Record 28 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 29 of Set 1 | new norfolk
Processing Record 30 of Set 1 | albany
Processing Record 31 of Set 1 | thompson
Processing Record 32 of Set 1 | cap malheureux
Processing Record 33 of Set 1 | cidreira
Processing Record 34 of Set 1 | toliary
City not found. Skipping...
Processing Record 35 of Set 1 | punta arenas
Processing Record 36 of Set 1 | lodja
Processing Record 37 of Set 1 | busselton
Processing Record 38 of Set 1 | tahta
Processing Record 39 of Set 1 | belushya guba
City not found. Skipping...
Processing Record 40 of Set 1 | bluff
Processing Record 41 of Set 1 | hilo
Processing Record 42 of Set 1 | tuatapere
Processing Record 43 of Set 1 | xichang
Processing Record 44 of Set 1 | kapaa
Processing Record 45 of Set 1 | north branch
Processing Record 46 of Set 1 | bara
-----------------------------
Data Retrieval Complete
-----------------------------

In [8]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Current Description,Max Temp,Humidity,Cloudiness,Wind Speed,Country
0,Ushtobe,45.2514,77.9838,overcast clouds,72.77,22,100,7.63,KZ
1,Coihaique,-45.5752,-72.0662,broken clouds,48.15,76,75,5.75,CL
2,Feijo,-8.1642,-70.3536,overcast clouds,89.11,55,91,1.66,BR
3,Tilichiki,60.4667,166.1000,broken clouds,23.67,93,53,7.16,RU
4,Hermanus,-34.4187,19.2345,scattered clouds,59.81,80,49,6.44,ZA
5,Khatanga,71.9667,102.5000,broken clouds,9.99,97,60,5.70,RU
6,Rikitea,-23.1203,-134.9692,light rain,75.78,77,56,13.42,PF
7,Port Alfred,-33.5906,26.8910,clear sky,62.19,77,2,5.99,ZA
8,Faanui,-16.4833,-151.7500,light rain,80.56,74,34,17.29,PF
9,Mataura,-46.1927,168.8643,broken clouds,63.48,86,84,4.25,NZ

In [9]:
new_city_data_df = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description"]

In [10]:
city_data_df = city_data_df.reindex(columns=new_city_data_df)

In [11]:
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Ushtobe,KZ,45.2514,77.9838,72.77,22,100,7.63,overcast clouds
1,Coihaique,CL,-45.5752,-72.0662,48.15,76,75,5.75,broken clouds
2,Feijo,BR,-8.1642,-70.3536,89.11,55,91,1.66,overcast clouds
3,Tilichiki,RU,60.4667,166.1000,23.67,93,53,7.16,broken clouds
4,Hermanus,ZA,-34.4187,19.2345,59.81,80,49,6.44,scattered clouds
5,Khatanga,RU,71.9667,102.5000,9.99,97,60,5.70,broken clouds
6,Rikitea,PF,-23.1203,-134.9692,75.78,77,56,13.42,light rain
7,Port Alfred,ZA,-33.5906,26.8910,62.19,77,2,5.99,clear sky
8,Faanui,PF,-16.4833,-151.7500,80.56,74,34,17.29,light rain
9,Mataura,NZ,-46.1927,168.8643,63.48,86,84,4.25,broken clouds

In [40]:
# Create the output file (CSV).
output_data_file = "WeatherPy_Database.csv"

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file)